/** @type {import('tailwindcss').Config} */
module.exports = {
  safelist: [
    'text-rose-500',
    'bg-rose-500',
    'to-rose-500',
    'text-purple-500',
    'bg-purple-500',
    'to-purple-500',
    'text-blue-500',
    'bg-blue-500',
    'to-blue-500',
    'text-green-300',
    'bg-green-300',
    'to-green-300',
    'text-orange-900',
    'bg-orange-900',
    'to-orange-900',
    'text-orange-300',
    'bg-orange-300',
    'to-orange-300',
    'text-black',
    'bg-black',
    'to-black',
    'text-gray-700',
    'bg-gray-700',
    'to-gray-700',
  ],
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
